- .github/workflows/publish.yml
- docusaurus-plugin-openapi/package.json
It should publish automatically to npm upon creating a new GitHub release (using SemVer). It converts the Git Tag (`refs/tags/v1.2.3`) to `1.2.3` and updates the `package.json` only for the publish step, and does not commit the bumped version back to the repository.
> Add CI/CD via GitHub Actions

- docusaurus-plugin-openapi/src/theme/ApiRequestBodyTable/index.js
Validates ApiRequestBodyTable when attribute body.content eq undefined
Fix error of `body.content===undefined` when using ApiRequestBodyTable to display some part of ApiStatusCodeTable.
_Important: This fix asumes that body.content is either an object with at least one element or is undefined alltogether._
> Validates ApiRequestBodyTable when attribute body.content is not defined

- packages/docusaurus-plugin-openapi/src/markdown/createSchemaTable.ts
- packages/docusaurus-plugin-openapi/src/markdown/createStatusCodesTable.ts
- packages/docusaurus-plugin-openapi/src/openapi/createExample.ts
> Add `allOf` JSON schema support

- demo/docusaurus.config.js
- packages/docusaurus-plugin-proxy/package.json
- packages/docusaurus-plugin-proxy/scripts/build.ts
- packages/docusaurus-plugin-proxy/src/index.ts
- packages/docusaurus-plugin-proxy/src/options.ts
- packages/docusaurus-plugin-proxy/src/plugin-proxy.d.ts
- packages/docusaurus-plugin-proxy/src/types.ts
- packages/docusaurus-plugin-proxy/tsconfig.json
- packages/docusaurus-preset-openapi/package.json
- packages/docusaurus-preset-openapi/src/index.ts
- packages/docusaurus-preset-openapi/src/preset-openapi.d.ts
- yarn.lock
This PR adds proxy support to the dev server, but won't be functional until the next version of Docusaurus
> Add proxy plugin package

- packages/docusaurus-plugin-openapi/package.json
- packages/docusaurus-plugin-openapi/src/sidebars/index.ts
This PR adds addition classnames to the api sidebar items to enable support for adding method tags via css magic (thanks @sserrata):
CSS used to generate the above screenshot:
```css
.api-method > .menu__link {
align-items: center;
justify-content: start;
}
.api-method > .menu__link::before {
width: 50px;
height: 20px;
font-size: 12px;
line-height: 20px;
text-transform: uppercase;
font-weight: 600;
border-radius: .25rem;
border: 1px solid;
margin-right: var(--ifm-spacing-horizontal);
text-align: center;
flex-shrink: 0;
}
.get > .menu__link::before {
content: "get";
border-color: var(--openapi-code-blue);
color:  var(--openapi-code-blue);
}
.put > .menu__link::before {
content: "put";
border-color: var(--openapi-code-orange);
color: var(--openapi-code-orange);
}
.post > .menu__link::before …
```
> Add sidebar item classname for method

- packages/docusaurus-plugin-openapi/package.json
- packages/docusaurus-plugin-openapi/src/openapi/openapi.ts
- yarn.lock
Resolves `allOf` references in the schema. Otherwise, I found that in some special cases the request body was missing.
> fix a few cases in which some content was not showing up due to allOf references

- packages/docusaurus-plugin-openapi/src/sidebars/index.ts
- packages/docusaurus-plugin-openapi/src/sidebars/sidebars.test.ts
This allows docusaurus-api to behave a bit more like docusaurus. When you have a folder with only a single file inside, docusaurus applies the `_category_` metadata to the item itself instead of creating an additional category.
This PR adds the same behavior for multi-spec pages.
Example: say you have this folder structure:
Right now, rendering this in a single page yields this:
With the proposed changes, you can use the `_category_` file to apply metadata to the inner category (let's say you want a custom title, or you want to set `collapsible=false`). It also removes the duplicated category, if the outer category only contains a single item. Result:
> Feature proposal: squashing categories

- demo/examples/food/burgers/openapi.yaml
- packages/docusaurus-plugin-openapi/src/markdown/createParamsTable.ts
- packages/docusaurus-plugin-openapi/src/markdown/createSchemaTable.ts
- packages/docusaurus-plugin-openapi/src/markdown/utils.ts
This PR fixes a build failure when one of the openapi specs includes a parameter with html special characters.
> Fix: escape html in param names

- packages/docusaurus-template-openapi/template.json
Docusaurus OpenAPI supports creating template projects using npm commands, such as `yarn create docusaurus-openapi my-website`.
Currently, the version of the template project is still `0.4.0`
https://github.com/cloud-annotations/docusaurus-openapi/blob/255c6df6ce7061683b8365af10bb1135d7e146aa/packages/docusaurus-template-openapi/template.json#L19
Try updating the version to the latest `0.6.0`.
Feel free to let me know if I'm missing something 💖 
@bourdakos1 @danieleds
> chore: update template version

- packages/docusaurus-plugin-openapi/src/markdown/createParamsTable.ts
Sometimes, a description is specified not as the attribute of a parameter but as the attribute of the parameter's schema. This PR ensures that the description is picked up correctly in both cases.
@bourdakos1
> ensure description from schema is not ignored

- packages/docusaurus-plugin-openapi/src/util.test.ts
- packages/docusaurus-plugin-openapi/src/util.ts
**Close #190** 
Use regex to check if it's an external link instead of using the URL and try/catch.
It can support **Windows** platforms..
> Fix: loading failed for local openapi json file on Windows

- demo/package.json
- packages/create-docusaurus-openapi/package.json
- packages/docusaurus-plugin-openapi/package.json
- packages/docusaurus-plugin-openapi/src/options.ts
- packages/docusaurus-plugin-openapi/src/types.ts
- packages/docusaurus-plugin-proxy/package.json
- packages/docusaurus-preset-openapi/package.json
- packages/docusaurus-template-openapi/template.json
- packages/docusaurus-theme-openapi/package.json
- packages/docusaurus-theme-openapi/src/theme/ApiPage/index.tsx
- yarn.lock
This PR fixes two breaking changes in beta.22 and later of Docusaurus.
- Theme icon assets have been moved to subfolders
- The type for `admonitions` has been changed
Docusaurus PR for reference: https://github.com/facebook/docusaurus/pull/7740
This PR also updates the dependencies for Docusaurus to support `^2.0.0`.
Resolves: #201
> fix(theme): new location for theme icons 

- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Server/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Server/slice.ts
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/buildPostmanRequest.ts
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/persistanceMiddleware.ts
- packages/docusaurus-theme-openapi/src/types.ts
This PR allows users to configure whether they want to store server variables within the browser, similar to what already happens with `authPersistance`.
@bourdakos1 I tried to keep the diff as small as possible
> Persist server variables configuration

- packages/docusaurus-template-openapi/template.json
Add `url` dependency to template.
Without this dependency will result in the `Module not found` error.
<details>
<summary>screenshot of running error</summary>
</details>
<details>
<summary>related package.json</summary>
```
{
"name": "docusaurus-openapi-example",
"version": "0.0.0",
"private": true,
"dependencies": {
"@docusaurus/core": "^2.0.0",
"docusaurus-preset-openapi": "0.6.0",
"@mdx-js/react": "^1.6.21",
"clsx": "^1.1.1",
"prism-react-renderer": "^1.2.1",
"react": "^17.0.1",
"react-dom": "^17.0.1"
},
"scripts": {
"docusaurus": "docusaurus",
"start": "docusaurus start",
"build": "docusaurus build",
"swizzle": "docusaurus swizzle",
"deploy": "docusaurus deploy",
"clear": "docusaurus clear",
"serve": "docusaurus serve",
"write-translations": "docusaurus write-translations", …
```
> fix: resolve fallback of url

- cypress/integration/test.spec.ts
- packages/docusaurus-plugin-openapi/src/openapi/openapi.ts
- packages/docusaurus-plugin-openapi/src/openapi/types.ts
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Authorization/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Authorization/slice.ts
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/buildPostmanRequest.ts
This PR adds support for authorizing with api keys in the http request headers (as seen in the [swagger example](https://user-images.githubusercontent.com/13732623/182992344-8f6eca06-8564-458d-b622-ed7dd1b234e5.png)).
When selecting "Authorize" the list of available header options will display as form inputs:
After the user specifies values, performing a request will append the values as headers to the request. 
This PR also adds a fallback to the OpenAPI spec to support 2.0 (when `securitySchemes` was a top-level object). 
I am unable to share the contents of the OpenAPI spec. Please let me know how I can help validate these changes for approval.
> feat(auth): authorize with api keys in header

- demo/docusaurus.config.js
I forgot to add this to the previous PR #202. We could add the `serverVariablesPersistance` config key in the demo, for documenting its existence.
> add example key `serverVariablesPersistance` in demo

- CHANGELOG.md
- demo/package.json
- lerna.json
- packages/create-docusaurus-openapi/package.json
- packages/docusaurus-plugin-openapi/package.json
- packages/docusaurus-plugin-proxy/package.json
- packages/docusaurus-preset-openapi/package.json
- packages/docusaurus-template-openapi/package.json
- packages/docusaurus-theme-openapi/package.json
Bumps the version for 0.6.2.
Let me know if I missed something here. I had issues with the changelog fetching the upstream, so I manually prepared the change based on what the script outputs.
> Prepare release v0.6.2

- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/buildPostmanRequest.ts
Values in query and path parameters were not url-encoded, resulting in invalid code snippets. This PR fixes that.
@bourdakos1
> fix: make sure to encode values in query and path parameters

- packages/docusaurus-plugin-openapi/src/openapi/openapi.ts
Was discussed here: https://github.com/cloud-annotations/docusaurus-openapi/pull/107#discussion_r772093391
Closes #232
> Fix invalid ignore pattern for underscore files

- packages/docusaurus-plugin-openapi/src/markdown/createRequestBodyTable.ts
- packages/docusaurus-plugin-openapi/src/markdown/createSchemaTable.ts
- packages/docusaurus-plugin-openapi/src/markdown/createStatusCodesTable.ts
- packages/docusaurus-theme-openapi/src/theme/ApiPage/styles.module.css
I thought it was a bit strange to display `REQUIRED` in response schemas. I added an option to disable it. I think it is a good default option, but we can let the user parametrize this.
What do you think?
> Hide required labels on response schemas

- packages/docusaurus-plugin-openapi/src/openapi/openapi.ts
The OpenAPI specification allows specifying a set of parameters for an entire path, instead of specifying them specifically for each operation within a path. See https://swagger.io/specification/#path-item-object
Previously, the parameters specified at the path level were ignored. This PR fixes that.
@bourdakos1
> Ensure path-level parameters are passed to the theme

- packages/docusaurus-plugin-openapi/src/plugin-openapi.d.ts
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Curl/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/index.tsx
Refs https://github.com/cloud-annotations/docusaurus-openapi/issues/236
Originally I was planning to submit a PR converting all of the imports, but what I quickly realised is that if you just do this without declaring a types module for each one, the compile process fails with
```
error TS2307: Cannot find module '@theme/ApiDemoPanel/Response' or its corresponding type declarations.
```
or whatever. This does increase the overhead of the job a bit so I have started off (somewhat selfishly 😇) by only converting the two components I am interested in swizzling. I can also confirm that doing this does make the nested components swizzle-able :tada:
> Convert some relative imports in theme package

- demo/examples/openapi-array-query-params.yaml
- packages/docusaurus-plugin-openapi/src/openapi/types.ts
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/ParamOptions/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/buildPostmanRequest.test.ts
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/buildPostmanRequest.ts
This PR is a bit of a mixed bag of related things.
1. There is an infinite render loop on pages that use query params, causing a `Maximum Update Depth Exceeded` error.
2. Respect the `maxItems` property for array query params.
3. OpenAPI supports number of different [styles for array query params](https://swagger.io/docs/specification/serialization/#query) via the `style` and `explode` properties. This PR adds compatibility for those.
> Fixes and enhancements for array query param handling

- CHANGELOG.md
- demo/package.json
- lerna.json
- packages/create-docusaurus-openapi/package.json
- packages/docusaurus-plugin-openapi/package.json
- packages/docusaurus-preset-openapi/package.json
- packages/docusaurus-template-openapi/package.json
- packages/docusaurus-template-openapi/template.json
- packages/docusaurus-theme-openapi/package.json
Looks like there are a few bits now backed up since 0.6.3. Hopefully I've done this right.
side note: I like the way you've set this project up so that contributors can propose a release by submitting a PR :) Cool way to both empower contributors and reduce overhead for maintainers.
> Prepare release v0.6.4

- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/FormMultiSelect/styles.module.css
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/FormSelect/styles.module.css
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/FormTextInput/styles.module.css
Using the default light theme, the form inputs aren't very obvious, especially the text inputs. We had feedback from a couple of users of our site indicating they didn't know there were form fields there at all.
This is less of an issue with the dark theme as the form inputs have a clearly different background colour.
This PR adds a thin border to form inputs when using the light theme.
**Before:**
**After:**
> add border to form inputs when using light them

- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Authorization/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Curl/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Execute/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/FloatingButton/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/FormFileUpload/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/ParamOptions/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Server/index.tsx
- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/index.tsx
As things stand at the moment, filling all the form fields and pressing Enter doesn't perform the "Execute" action. You have to actually click the "Execute" button with a mouse.
This PR enables performing the "Execute" action with the Enter key.
In order to do this, I've:
- Added a `<form>` container
- Made the "Execute" button `type="submit"`
- Made all the other buttons inside the form (for showing and hiding things) `type="button"`
- Disabled the form submit action
> allow pressing enter to perform the 'Execute' action

- packages/docusaurus-plugin-openapi/src/markdown/createParamsTable.ts
The main thing here is to format the example value distinct from the other documentation text.
I think given these are values that would be passed in as a path or query param, using a `<code>` block is a reasonable, but open to other suggestions on it.
> render examples in a `<code>` block

- packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/buildPostmanRequest.ts
This commit fixes an issue where utf-16 encoded surrogated pair could crash the page when inserted as input.
The commit adds `endsWithHalfSurrogatePair` to check for half pair and `safeEncodeURIComponent` to ignore half surrogated pair before passing it to `encodeURIComponent`.
I replaced `encodeURIComponent` with `safeEncodeURIComponent` to solve the bug.
I run lint, testing and and cypress and everything seems ok.
I also tested before/after changes by hand to make sure the bug is solved.
Fixes #260
> Fix: Page crash on half surrogate pair

- demo/docusaurus.config.js
- demo/package.json
- packages/create-docusaurus-openapi/package.json
- packages/docusaurus-plugin-openapi/package.json
- packages/docusaurus-plugin-openapi/src/index.ts
- packages/docusaurus-plugin-openapi/src/options.ts
- packages/docusaurus-plugin-openapi/src/types.ts
- packages/docusaurus-plugin-proxy/package.json
- packages/docusaurus-preset-openapi/package.json
- packages/docusaurus-template-openapi/template.json
- packages/docusaurus-theme-openapi/package.json
- packages/docusaurus-theme-openapi/src/index.ts
- yarn.lock
Docusaurus 3.6 introduced some changes which broke the OpenAPI plugin (see #293). This PR fixes that issue, ~~by using the new `createMDXLoaderItem` API to create the rule for `@docusaurus/mdx-loader` (see https://github.com/facebook/docusaurus/pull/10450)~~ by adding the missing `siteDir` property to the `mdx-loader` options.
This PR also adds support for Docusaurus Faster (https://github.com/facebook/docusaurus/issues/10556).
Fixes #293
> Update to Docusaurus 3.6

- CHANGELOG.md
- demo/package.json
- lerna.json
- packages/create-docusaurus-openapi/package.json
- packages/docusaurus-plugin-openapi/package.json
- packages/docusaurus-plugin-proxy/package.json
- packages/docusaurus-preset-openapi/package.json
- packages/docusaurus-template-openapi/package.json
- packages/docusaurus-template-openapi/template.json
- packages/docusaurus-theme-openapi/package.json
Looks like last time the minimum docusaurus version was bumped (to Docusaurus 3.2 in release 0.7.4) this was done in a patch release. I've done the same here.
> Prepare release v0.7.6
